import type { ProviderConfig, TimingMetrics } from '../core/types.js';
import type { Provider } from '../core/provider.js';
import { registerProvider } from '../core/provider.js';

export type MockProfile = 'fast' | 'default' | 'slow' | 'variable';

const PROFILES: Record<MockProfile, { baseMs: number; variance: number; tokenRate: number }> = {
  fast: { baseMs: 100, variance: 20, tokenRate: 200 },
  default: { baseMs: 500, variance: 100, tokenRate: 50 },
  slow: { baseMs: 2000, variance: 500, tokenRate: 10 },
  variable: { baseMs: 800, variance: 400, tokenRate: 30 },
};

export interface MockProviderConfig extends ProviderConfig {
  profile?: MockProfile;
}

export class MockProvider implements Provider {
  public readonly name: string;
  public readonly model: string;
  private profile: MockProfile;

  constructor(config: MockProviderConfig) {
    this.name = config.name;
    this.model = config.model;
    this.profile = config.profile || 'default';
  }

  async complete(prompt: string): Promise<{ text: string; metrics: TimingMetrics }> {
    const settings = PROFILES[this.profile];
    // Deterministic latency based on prompt length + profile
    const seed = Buffer.from(prompt, 'utf-8').reduce((a, b) => a + b, 0);
    const jitter = ((seed * 7) % settings.variance) - settings.variance / 2;
    const totalLatencyMs = settings.baseMs + jitter;
    const timeToFirstTokenMs = totalLatencyMs * 0.3;
    const streamingLatencyMs = totalLatencyMs - timeToFirstTokenMs;

    // Generate deterministic mock response
    const mockResponses = [
      "The quick brown fox jumps over the lazy dog. This is a benchmark response generated by the mock provider for consistent testing.",
      "In software engineering, design patterns are reusable solutions to common problems. They serve as templates that can be applied across different projects.",
      "Machine learning is a subset of artificial intelligence that enables systems to learn and improve from experience without being explicitly programmed.",
      "The Fibonacci sequence is a series where each number is the sum of the two preceding ones, typically starting with 0 and 1.",
      "Benchmarking is the practice of measuring performance against established standards to identify areas for improvement.",
    ];
    const responseIndex = seed % mockResponses.length;
    const text = mockResponses[responseIndex];
    const tokenCount = text.split(/\s+/).length;
    const tokensPerSecond = tokenCount / (streamingLatencyMs / 1000);

    return {
      text,
      metrics: {
        timeToFirstTokenMs,
        totalLatencyMs,
        streamingLatencyMs,
        tokensPerSecond,
        tokenCount,
      },
    };
  }
}

registerProvider('mock', (config: ProviderConfig) =>
  new MockProvider(config as MockProviderConfig),
);
